### változók
@protocol = http://
@hostname = localhost
@port = 8000
@host = {{protocol}}{{hostname}}:{{port}}
### @token =2|4870lH49Na2nZ1W14SjOjSRW8vW2FSVtSXmEN86W13e71c1d"


### login
# @name login
POST {{host}}/api/users/login
Accept: application/json
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "123"
}

###
@token = {{login.response.body.data.token}}

### logout user
POST  {{host}}/api/users/logout
Accept: application/json
Authorization: Bearer {{token}}


### get users
GET  {{host}}/api/users
Accept: application/json
Authorization: Bearer {{token}}

### get user by id
GET  {{host}}/api/users/1
Accept: application/json
Authorization: Bearer {{token}}

### post user
POST {{host}}/api/users
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "name":  "Vásárló2",
    "email": "vasarlo2@example.com",
    "password": "123"
}

### patch user
PATCH {{host}}/api/users/2
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "name": "No Boss"
}

### delete user
DELETE {{host}}/api/users/2
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}


### User csak önmagát törölheti
DELETE {{host}}/api/usersme
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

### A bejelentkezett user a jelszavát módosítja
PATCH {{host}}/api/usersme
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "name": "vasarlo2",
    "email": "vasarlo2@example.com"
}

### A bejelentkezett user egy adatát módosítja. A role tiltott
PATCH {{host}}/api/usersme
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
     "name": "admin1"
}

### A bejelnkezett felhasználó jelszó cseréje
PATCH {{host}}/api/usersmeupdatepassword
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "oldpassword": "ronaldo",
    "newpassword": "123",
    "newpassword_confirmation": "123"
}

### A bejelentkezett user önmagát lekérheti
GET  {{host}}/api/usersme
Accept: application/json
Authorization: Bearer {{token}}



### teszt
get {{host}}/api/x

### get products
get {{host}}/api/products
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### get product by id
get {{host}}/api/products/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### post products
POST  {{host}}/api/products
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "category": "Bogyós",
    "name": "f3333xx",
    "description": "Kézzel termelt egészség",
    "picture": "https:\/\/hur.webmania.cc\/img\/malna.jpg",
    "price": 8000,
    "stock": 22
}

### delete product by id
delete {{host}}/api/products/104
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


### post products
PATCH {{host}}/api/products/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


{
    "price": 1002,
    "stock": "eee"
}



###-----Breeds----------------------------------------------------------------------
### get Breeds
GET  {{host}}/api/breeds
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### get breeds by id
get {{host}}/api/breeds/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### post breeds
POST  {{host}}/api/breeds
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
"breed":"Test222"
}

###Patch breed by id
PATCH  {{host}}/api/breeds/31
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "breed": "tesztbreed"
}


### delete breed by id
delete {{host}}/api/breeds/31
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}



###------Colors----------------------------------------------------------------------
### get color
GET  {{host}}/api/colors
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### get color by id
GET  {{host}}/api/colors/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### post color
POST  {{host}}/api/colors
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
"colorName":"Test color3"
}

###Patch color by id
PATCH  {{host}}/api/colors/19
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "colorName": "teszt1"
}

### delete color by id
delete {{host}}/api/colors/19
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


###-------Medicines---------------------------------------------------------------------
### get medicines
GET  {{host}}/api/medicines
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### get medicine by id
GET  {{host}}/api/medicines/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### post medicine
POST  {{host}}/api/medicines
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
"medicineName":"Test2"
}

###Patch medicines by id
PATCH  {{host}}/api/medicines/22
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "medicineName": "teszt3"
}

### delete medicines by id
delete {{host}}/api/medicines/22
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}



###------Dogs----------------------------------------------------------------------
### get all dogs
GET  {{host}}/api/dogs
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### get dog by id
GET  {{host}}/api/dogs/200
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### post dog
POST  {{host}}/api/dogs
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
"breedId":"11",
"dogName":"Buksi",
"userId":"3",
"dateOfBirth":"2026-01-27",
"chipNumber":"676767676767676",
"gender":"0",
"colorId":"11",
"weight":"30",
"teeth":"1"
}


###Patch dog by id
PATCH  {{host}}/api/dogs/201
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "dogName": "teszt kutya1"
}

### delete dog by id
delete {{host}}/api/dogs/201
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}


###------Vaccinations---------------------------------------------------------------
### get all vaccination
GET  {{host}}/api/vaccinations
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### get vaccination by id
GET  {{host}}/api/vaccinations/2
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### post vaccination
POST  {{host}}/api/vaccinations
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "dogId": "1",
    "medicineId":"1",
    "timeOfVaccination":"2020-01-01",
    "vaccinationPrice":"1000000"
}

###Patch vaccination by id
PATCH  {{host}}/api/vaccinations/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
"vaccinationPrice":5555
}

### delete vaccination by id
delete {{host}}/api/vaccinations/201
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}



###------Photos---------------------------------------------------------------
### get all photos
GET  {{host}}/api/photos
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### get photo by id
GET  {{host}}/api/photos/2
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### post photo
POST  {{host}}/api/photos
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
"dogId":2,
"imgUrl":"https://fbggerg"
}

###Patch photo by id
PATCH  {{host}}/api/photos/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
"imgUrl":"patch teszt"
}

### delete photo by id
delete {{host}}/api/photos/201
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
